name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Decrypting dependencies
        run: |
          sudo apt update && sudo apt install -y git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Add required properties
        run: |
          cat > local.properties <<EOF
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          DEBUG_API_BASE_URL=http://localhost/api/
          DEBUG_WEB_SOCKET_BASE_URL=ws://localhost/
          EOF

      - name: Run build
        run: ./gradlew build

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Decrypting dependencies
        run: |
          sudo apt update && sudo apt install -y git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Add required properties
        run: |
          cat > local.properties <<EOF
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          DEBUG_API_BASE_URL=http://localhost/api/
          DEBUG_WEB_SOCKET_BASE_URL=ws://localhost/
          EOF
      - name: Run tests
        run: ./gradlew test

  instrumentation-test:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 28, 29, 30, 31, 32, 33 ]
        target: [ google_apis_playstore ]
        architecture: [ x86_64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Decrypting dependencies
        run: |
          brew update && brew install git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Add required properties
        run: |
          cat > local.properties <<EOF
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          DEBUG_API_BASE_URL=http://localhost/api/
          DEBUG_WEB_SOCKET_BASE_URL=ws://localhost/
          EOF

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.architecture }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.architecture }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.architecture }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest