name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for filing an issue in the repository. We appreciate your feedback and will do our best to respond promptly."
          pr-message: "Welcome to the project, new contributor! We appreciate your first pull request (PR) and will review it as soon as possible. Thank you for your interest in this project and your valuable contributions."
