name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello new contributor! Thanks for taking the time to file this issue in the repository. We will give our best to get back on time."
          pr-message: "Hello new contributor! We noticed this is your first PR in this repository. We will take a look at it ASAP. Thanks for your valued contributions and for showing interest in this great project."
