name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for filing an issue in the repository. We appreciate your feedback and will do our best to respond promptly."
          pr-message: "Hello new contributor! We noticed this is your first PR in this repository. We will take a look at it ASAP. Thanks for your valuable contributions and for showing interest in this great project."
